import { FormEvent, useEffect, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useDispatch } from 'react-redux';
import { setPageTitle } from '../../store/themeConfigSlice';
import { adminApi } from '../../services/admin.service';
import { getErrorMessage } from '../../services/api';
import { DetailFacts, FormField, FormSection, StatusBadge } from '../../components/Admin/FormPrimitives';
import { confirmAction, showAlert } from '../../utils/alerts';
const STATUSES = ['NEW', 'REVIEWING', 'PLANNED', 'IMPLEMENTED', 'DECLINED'];
export default function SuggestionDetail() { const { id } = useParams<{ id: string }>(); const navigate = useNavigate(); const dispatch = useDispatch(); const [item, setItem] = useState<any>(); const [status, setStatus] = useState(''); const [note, setNote] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const load = async () => { if (!id) return; try { const data = await adminApi.getSuggestion(id) as any; setItem(data); setStatus(data.status); setNote(data.adminNote || ''); dispatch(setPageTitle(data.title)); } catch (err) { showAlert(getErrorMessage(err), 'error'); } finally { setLoading(false); } }; useEffect(() => { load(); // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [id]); if (loading) return <div className="panel">Loading suggestion...</div>; if (!item) return <div className="panel">Suggestion not found</div>; const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); try { await adminApi.updateSuggestion(id!, { status, adminNote: note }); await load(); showAlert('Suggestion updated successfully'); } catch (err) { showAlert(getErrorMessage(err), 'error'); } finally { setBusy(false); } }; const remove = async () => { if (!await confirmAction('Delete this suggestion?')) return; await adminApi.deleteSuggestion(id!); navigate('/admin/suggestions'); }; return <div><div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><Link to="/admin/suggestions" className="text-primary">← Suggestions & Ideas</Link><h2 className="mt-3 text-xl font-semibold">{item.title}</h2><p className="mt-1 text-white-dark">{item.details}</p></div><div className="flex gap-2"><StatusBadge status={item.status} /><button className="btn btn-outline-danger" onClick={remove}>Delete</button></div></div><div className="panel mb-5"><h5 className="mb-4 text-lg font-semibold">Customer details</h5><DetailFacts items={[{ label: 'Name', value: item.customer?.name || '—' }, { label: 'Email', value: item.customer?.email || '—' }, { label: 'Mobile', value: item.customer?.mobile || '—' }, { label: 'Category', value: item.category }, { label: 'Received', value: new Date(item.createdAt).toLocaleString() }]} /></div><form className="panel" onSubmit={submit}><FormSection title="Review suggestion"><div className="grid gap-4 sm:grid-cols-2"><FormField label="Status" required><select className="form-select" value={status} onChange={(e) => setStatus(e.target.value)}>{STATUSES.map((s) => <option key={s}>{s}</option>)}</select></FormField><FormField label="Admin note"><textarea className="form-textarea sm:col-span-2" rows={5} value={note} onChange={(e) => setNote(e.target.value)} /></FormField></div></FormSection><div className="mt-5 flex justify-end"><button className="btn btn-primary" disabled={busy}>{busy ? 'Saving...' : 'Save review'}</button></div></form></div>; }
